/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Chatbot: typeof import('./components/Chatbot.vue')['default']
    ChatBotComponent: typeof import('./components/ChatBotComponent.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    Drafts: typeof import('./components/Drafts.vue')['default']
    FootBar: typeof import('./components/FootBar.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    MyPosts: typeof import('./components/MyPosts.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    Prices: typeof import('./components/Prices.vue')['default']
    README: (typeof import("./components/README.md"))["default"]
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerEvent: typeof import('./components/ServerEvent.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    TextBlock: typeof import('./components/TextBlock.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheToolbar: typeof import('./components/TheToolbar.vue')['default']
    TipTap: typeof import('./components/TipTap.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}
